# Project

## Estadística de Producción Agrícola

In [7]:
import pandas as pd
import numpy as np
from numpy import NaN
import matplotlib.pyplot as plt

## Introducción:

El proposito de este analisis es....

In [8]:
data_2020 = pd.read_csv("data/project_v4/data/Cierre_agricola_mun_2020.csv", 
                        encoding="latin1")

data_2020.head()

,Anio,Idestado,Nomestado,Idddr,Nomddr,Idcader,Nomcader,Idmunicipio,Nommunicipio,Idciclo,...,Nomunidad,Idcultivo,Nomcultivo Sin Um,Sembrada,Cosechada,Siniestrada,Volumenproduccion,Rendimiento,Precio,Valorproduccion
0,2020,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,5490000,Avena forrajera en verde,1175.00,1175.00,0.0,32571.0,27.72,571.74,18622143.54
1,2020,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,5670000,Brócoli,15.00,15.00,0.0,295.6,19.71,3950.00,1167620.00
2,2020,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,2,...,Tonelada,5490000,Avena forrajera en verde,160.00,160.00,0.0,4352.0,27.20,586.25,2551360.00
3,2020,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,2,...,Tonelada,5670000,Brócoli,20.00,20.00,0.0,306.6,15.33,4166.40,1277418.24
4,2020,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,2,...,Tonelada,6120000,Chile verde,6.48,6.48,0.0,313.5,48.38,14279.71,4476687.99

In [9]:

data_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28661 entries, 0 to 28660
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Anio                28661 non-null  int64
 1   Idestado            28661 non-null  int64
 2   Nomestado           28661 non-null  object
 3   Idddr               28661 non-null  int64
 4   Nomddr              28661 non-null  object
 5   Idcader             28661 non-null  int64
 6   Nomcader            28661 non-null  object
 7   Idmunicipio         28661 non-null  int64
 8   Nommunicipio        28661 non-null  object
 9   Idciclo             28661 non-null  int64
 10  Nomcicloproductivo  28661 non-null  object
 11  Idmodalidad         28661 non-null  int64
 12  Nommodalidad        28661 non-null  object
 13  Idunidadmedida      28661 non-null  int64
 14  Nomunidad           28661 non-null  object
 15  Idcultivo           28661 non-null  int64
 16  Nomcultivo Sin Um   28661 non-null  object
 17  Sembrada            28661 non-null  float64
 18  Cosechada           28661 non-null  float64
 19  Siniestrada         28661 non-null  float64
 20  Volumenproduccion   28661 non-null  float64
 21  Rendimiento         28661 non-null  float64
 22  Precio              28661 non-null  float64
 23  Valorproduccion     28661 non-null  float64
dtypes: float64(7), int64(9), object(8)
memory usage: 5.2+ MB

In [11]:
data_2019 = pd.read_csv("https://raw.githubusercontent.com/IA-Center-Python/project_ds_python_v4-alanponce/main/data/Cierre_agricola_mun_2019.csv?token=GHSAT0AAAAAAB3ADV76LDPFGO2DODQXLQYKY63CZDA",
                       encoding="latin1")

data_2019.head()

,Anio,Idestado,Nomestado,Idddr,Nomddr,Idcader,Nomcader,Idmunicipio,Nommunicipio,Idciclo,...,Nomunidad,Idcultivo,Nomcultivo Sin Um,Sembrada,Cosechada,Siniestrada,Volumenproduccion,Rendimiento,Precio,Valorproduccion
0,2019,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,5490000,Avena forrajera en verde,1525.0,1525.0,0.0,41182.48,27.00,567.67,23378058.42
1,2019,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,5900000,Cebada forrajera en verde,35.0,35.0,0.0,945.00,27.00,575.71,544045.95
2,2019,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,9090000,Triticale forrajero en verde,364.0,364.0,0.0,12037.00,33.07,569.82,6858923.34
3,2019,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,...,Tonelada,15050000,Pastos y praderas,460.0,460.0,0.0,22808.00,49.58,552.79,12608034.32
4,2019,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,2,...,Tonelada,5490000,Avena forrajera en verde,146.0,146.0,0.0,4013.60,27.49,601.36,2413618.50

## Analsis Exploratorio

El objetivo de este analisis es x, y z.


Nos focalizaremos primeramente en identificar cuales son los paises participantes de esta encuesta

In [6]:
data_2020["Nomestado"].value_counts()

Oaxaca                 4374
Puebla                 2663
Jalisco                1788
Veracruz               1736
Michoacán              1713
México                 1527
Guerrero               1341
Guanajuato             1220
Hidalgo                1015
Sonora                  963
Chiapas                 956
Zacatecas               918
San Luis Potosí         825
Chihuahua               770
Tlaxcala                708
Morelos                 679
Sinaloa                 670
Yucatán                 662
Durango                 605
Tamaulipas              541
Nayarit                 436
Coahuila                384
Querétaro               310
Nuevo León              294
Aguascalientes          254
Colima                  242
Tabasco                 224
Campeche                218
Baja California         215
Quintana Roo            149
Baja California Sur     148
Ciudad de México        113
Name: Nomestado, dtype: int64

Podemos apreciar que este conjunto de datos tenemos .....

## Resultados:

En esta sección se plantearán los resultados de su análisis......

## Conclusion:

En esta sección se indicarán sus conclusiones....

## Referencias: